import Head from 'next/head'
import Header from '../components/header'
import Container from '../components/container'
import Image from 'next/image'
import Rating from '../components/rating'
import { AiOutlineSearch, AiFillStar, AiOutlineStar } from 'react-icons/ai'
import { BsCart } from 'react-icons/bs'
import { useCart } from '../context/cartContext'

const products = [{
  "id": 1,
  "title": "Coca Cola Zero",
  "price": 3.50,
  "description": "Your perfect pack for everyday use and walks in the forest. Stash your laptop (up to 15 inches) in the padded sleeve, your everyday",
  "category": "men's clothing",
  "image": "/imgs/coca.jpg",
  "rating": {
    "rate": 5,
    "count": 54
    }
  },
  {
  "id": 2,
  "title": "KitKat",
  "price": 2.20,
  "description": "Your perfect pack for everyday use and walks in the forest. Stash your laptop (up to 15 inches) in the padded sleeve, your everyday",
  "category": "men's clothing",
  "image": "/imgs/kitkat.jpg",
  "rating": {
    "rate": 3.9,
    "count": 150
    }
  },
  {
  "id": 3,
  "title": "Doritos Wasabi",
  "price": 4,
  "description": "Your perfect pack for everyday use and walks in the forest. Stash your laptop (up to 15 inches) in the padded sleeve, your everyday",
  "category": "men's clothing",
  "image": "/imgs/doritos.jpg",
  "rating": {
    "rate": 2.9,
    "count": 80
    }
  },
  {
  "id": 4,
  "title": "Refrigerante Pepsi",
  "price": 3.50,
  "description": "Your perfect pack for everyday use and walks in the forest. Stash your laptop (up to 15 inches) in the padded sleeve, your everyday",
  "category": "men's clothing",
  "image": "/imgs/pepsi.png",
  "rating": {
    "rate": 3,
    "count": 60
    }
  },
  {
  "id": 5,
  "title": "Snicker Fruta e Amedoin",
  "price": 2,
  "description": "Your perfect pack for everyday use and walks in the forest. Stash your laptop (up to 15 inches) in the padded sleeve, your everyday",
  "category": "men's clothing",
  "image": "/imgs/snicker.jpg",
  "rating": {
    "rate": 2,
    "count": 120
    }
  },
  {
  "id": 6,
  "title": "Biscoito Oreo",
  "price": 3,
  "description": "Your perfect pack for everyday use and walks in the forest. Stash your laptop (up to 15 inches) in the padded sleeve, your everyday",
  "category": "men's clothing",
  "image": "/imgs/oreo.jpg",
  "rating": {
    "rate": 3.9,
    "count": 30
    }
  }
]

const ProductCard = ({ product, onClick }) => {
  return (
    <div className="border rounded-xl shadow-md">
      <div className="h-60">
        <img src={product.image} className="w-full h-full object-cover rounded-t-xl" alt={product.title} />
      </div>
      <div className="p-4">
        <h1 className="text-lg font-medium truncated-1-line">{product.title}</h1>
        <div className="my-2"><Rating rating={product.rating} /></div>
        <p className="truncated-2-lines">{product.description}</p>
        <span className="text-gray-300 text-sm">Restam 15 unidades no estoque</span>
        <button className="flex justify-center items-center gap-x-3 bg-primary mt-2 rounded-2xl w-full py-2 text-white font-medium text-xl border-2 transition-all duration-400 border-primary hover:bg-transparent hover:text-gray-600" onClick={onClick}>
          <BsCart className="text-2xl" /> R$ {product.price.toFixed(2)}
        </button>
      </div>
    </div>
  )
}

const SearchBox = () => {
  return (
    <div className="flex items-center gap-x-2">
      <input type="search" className="rounded-2xl py-3 px-4 border-2 outline-none w-full transition-all duration-500 focus:border-primary" placeholder="Busque por um produto" />
      <button className="p-3 border-2 border-primary-lighter bg-primary-lighter text-white transition-all duration-400 rounded-xl hover:bg-transparent hover:text-gray-600">
        <AiOutlineSearch className="text-2xl" />
      </button>
    </div>
  )
}

export default function Products() {
  const { items, total, addItem } = useCart()
  
  return (
    <>
      <Head>
        <title>Produtos da Forkos Food</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Header />
      
      <main className="py-8">
        <Container>
          <SearchBox />
          <h1 className="text-3xl font-medium my-12 text-gray-800">Produtos</h1>
          <ul className="grid md:grid-cols-4 gap-x-3 gap-y-4">
            {products.map((product) => (
              <li key={product.id}>
                <ProductCard
                  product={product}
                  onClick={() => addItem(product)}
                />
              </li>
            ))}
          </ul>
        </Container>
      </main>
    </>
  )
}